FROM node:18.14-alpine AS build

WORKDIR /app

COPY package* yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . ./
RUN yarn y:build

FROM node:18.14-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile && yarn cache clean
COPY --from=build /app/dist /app/dist
CMD ["yarn", "start"]